###POST create a user- requires no authentication.
POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "test1@gmail.com",
  "password": "test1111",
  "username": "test0000"
}

###PATCH create a user- requires no authentication.
PATCH http://localhost:8080/users
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

{
  "email": "test1@gmail.com",
  "password": "test1111",
  "username": "test0000"
}

###DELETE user
POST http://localhost:8080/users
Authorization: Basic {{username}} {{password}}
